apiVersion: v1
kind: Pod
metadata:
  name: httpdns
spec:
  selector:
    anand: "true"
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
