apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  containers:
  - name: myapp
    image: httpd
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-anty-affinity
spec:
  affinity:
     podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - httpd
          topologyKey: kubernetes.io/hostname
  containers:
  - name: with-pod-anty-affinity
    image: k8s.gcr.io/pause:2.0