apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: demo
        image: centos
        command: ["sleep", "30" ]
      restartPolicy: Never
  backoffLimit: 4