apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: Anand
    image: anandsatish/nihal
  imagePullSecrets:
  - name: regcred
    ports:
        - containerPort: 8080

    