apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: Anand
    image: anandsatish/nihal
  imagePullSecrets:
  - name: regcred
    command: ["sleep", "30000" ]
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "100m"
    ports:
        - containerPort: 8080

    