apiVersion: apps/v1beta1 
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: 
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: Pvc-demo
spec:
  containers:
  - name: demo
    image: centos
    command: ["sleep" ,"30000"]
    volumeMounts:
    - name: mariadb-pvc
      mountPath: "/opt/data"
  volumes:
    - name: mariadb-pvc
      PersistentVolumeClaim:
        claimName: mariadb-pvc
