  Type: AWS::EC2::Instance
  Properties: 
    AvailabilityZone: ap-southeast-1a
    ImageId: 0adbe59da7d24a349
    InstanceType: t2.micro
    KeyName: anand
    Tags: 
      - Name
    BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
      
