--- 
 apiVersion: v1
 kind: Service
 metadata:
     name: gameoflife-svc
 spec:
   type: ClusterIP
   selector:
     app: gameoflife
   ports:
     - port: 8080
       targetport: 8080 
--- 
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vprofile-v1
      labels:
        app: gameoflife
    spec:
      containers:
          - name: demo
            image: anandsatish/nihal
            ports:
              - containerPort: 8080
---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress-service
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
    spec:
      rules:
        - http:
            paths:
              - path: /?(.*)
                backend:
                  serviceName: gameoflife-svc
                  servicePort: 8080
 