apiVersion: v1
kind: Pod
metadata:
  name: httpd
  label:
    app: httpd
spec:
  containers:
  - name: demo
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "100m"
---

apiVersion: v1
kind: Service
metadata:
  name: anand-service
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      