apiVersion: v1
kind: Pod
metadata:
  name: httpd-env
  labels:
    name: env
spec:
  containers:
  - name: httpd
    image: httpd
    env:
      - name: project-1
        value: xyz
        name: project-2
        value: pli
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
