apiVersion: v1
kind: Pod
metadata:
  name: tolerated
  labels:
    name: httpd
spec:
  tolerations:
- key: "security"
  operator: "Equal"
  value: "none"
  effect: "NoSchedule"
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
