apiVersion: v1
kind: Pod
metadata:
  name: non-tolerated-pod
  labels:
    name: httpd
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
