apiVersion: v1
kind: Pod
metadata:
  name: resource
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    requests:
        memory: "64Mi"
        CPU: "128m"    
    ports:
      - containerPort: 80
